/**
 * Catalogo de juegos inspirado en TikControl (game-mods + pestaña Gaming).
 * nativeModule: integracion completa en Live Control Studio.
 * catalog: comandos de referencia / proxima integracion.
 */
import { withTikControlGameCover } from './tikcontrolGameCovers.js'
export const GAMING_LIBRARY_GROUPS = [
  { id: 'featured', label: 'Destacados', order: 0 },
  { id: 'minecraft', label: 'Minecraft', order: 1 },
  { id: 'gta', label: 'GTA V', order: 2 },
  { id: 'tikcontrol', label: 'Mods TikControl', order: 3 },
  { id: 'steam', label: 'Steam y otros', order: 4 },
  { id: 'coop', label: 'Co-op y terror', order: 5 },
]

function entry({
  id,
  name,
  group,
  accent = '#7a5cff',
  coverUrl = '',
  status = 'catalog',
  nativeModule = '',
  tags = [],
  summary = '',
  mode = '',
}) {
  return {
    id,
    name,
    group,
    accent,
    coverUrl,
    status,
    nativeModule,
    tags,
    summary,
    mode,
  }
}

const GAMING_CATALOG_RAW = [
  entry({
    id: 'minecraft',
    name: 'Minecraft',
    group: 'featured',
    accent: '#7fd26b',
    coverUrl: '/game-covers/minecraft.jpg',
    status: 'native',
    nativeModule: 'minecraft',
    tags: ['RCON', 'Bedrock Box', 'OneBlock'],
    summary: 'Comandos, presets Bedrock Box, chat espejo y bridge local.',
    mode: 'RCON / Mod',
  }),
  entry({
    id: 'gtav-chaos',
    name: 'GTA V Chaos Mod',
    group: 'featured',
    accent: '#ff8a5b',
    coverUrl: '/game-covers/gta-v-caratula-fan.jpg',
    status: 'native',
    nativeModule: 'gta',
    tags: ['ChaosMod', 'Webhook'],
    summary: 'Efectos ChaosMod y acciones por gifts para GTA V.',
    mode: 'ChaosMod',
  }),
  entry({
    id: 'tikcontrol-bedrockbox',
    name: 'Bedrock Box',
    group: 'minecraft',
    accent: '#55e3d6',
    status: 'native',
    nativeModule: 'minecraft',
    tags: ['Arena', 'TNT'],
    summary: 'Minijuego de caja Bedrock con presets rapidos.',
    mode: 'Plugin S2E',
  }),
  entry({
    id: 'tikcontrol-oneblock',
    name: 'OneBlock',
    group: 'minecraft',
    accent: '#c28cff',
    status: 'native',
    nativeModule: 'minecraft',
    tags: ['Challenge'],
    summary: 'Retos OneBlock con comandos del panel.',
    mode: 'Plugin S2E',
  }),
  entry({
    id: 'tikcontrol-sandbox',
    name: 'TikControl Sandbox',
    group: 'tikcontrol',
    accent: '#60a5fa',
    status: 'catalog',
    summary: 'Mundo sandbox controlado por la audiencia.',
    mode: 'Mod TikControl',
  }),
  entry({
    id: 'tikcontrol-farm',
    name: 'TikControl Farm',
    group: 'tikcontrol',
    accent: '#86efac',
    status: 'catalog',
    summary: 'Granja interactiva para streams.',
    mode: 'Mod TikControl',
  }),
  entry({
    id: 'tikcontrol-parkour',
    name: 'TikControl Parkour',
    group: 'tikcontrol',
    accent: '#fbbf24',
    status: 'catalog',
    summary: 'Parkour con eventos por regalos.',
    mode: 'Mod TikControl',
  }),
  entry({
    id: 'tikcontrol-koth',
    name: 'King of the Hill',
    group: 'tikcontrol',
    accent: '#f97316',
    status: 'catalog',
    summary: 'Captura la zona con tu chat.',
    mode: 'Mod TikControl',
  }),
  entry({
    id: 'tikcontrol-survival',
    name: 'Survival Chaos',
    group: 'tikcontrol',
    accent: '#34d399',
    status: 'catalog',
    summary: 'Supervivencia con eventos aleatorios.',
    mode: 'Mod TikControl',
  }),
  entry({
    id: 'tikcontrol-towerdefense',
    name: 'Tower Defense',
    group: 'tikcontrol',
    accent: '#a78bfa',
    status: 'catalog',
    summary: 'Oleadas y torres activadas por gifts.',
    mode: 'Mod TikControl',
  }),
  entry({
    id: 'tikcontrol-cubo',
    name: 'TikControl Cubo',
    group: 'tikcontrol',
    accent: '#38bdf8',
    status: 'catalog',
    summary: 'Minijuego del cubo en pantalla.',
    mode: 'Mod TikControl',
  }),
  entry({
    id: 'supermarket-together',
    name: 'Supermarket Together',
    group: 'steam',
    accent: '#4ade80',
    status: 'catalog',
    summary: 'Caos en el supermercado con tu comunidad.',
    mode: 'Steam',
  }),
  entry({
    id: 'supermarketsimulator',
    name: 'Supermarket Simulator',
    group: 'steam',
    accent: '#22d3ee',
    status: 'catalog',
    summary: 'Gestiona la tienda con eventos del live.',
    mode: 'Steam',
  }),
  entry({
    id: 'subnautica',
    name: 'Subnautica',
    group: 'steam',
    accent: '#2dd4bf',
    status: 'catalog',
    summary: 'Exploracion submarina con comandos.',
    mode: 'Steam',
  }),
  entry({
    id: 'subnautica2',
    name: 'Subnautica 2',
    group: 'steam',
    accent: '#14b8a6',
    status: 'catalog',
    summary: 'Secuela con integracion de comandos.',
    mode: 'Steam',
  }),
  entry({
    id: 're4',
    name: 'Resident Evil 4',
    group: 'steam',
    accent: '#ef4444',
    status: 'catalog',
    summary: 'Armas y eventos para runs de terror.',
    mode: 'Steam',
  }),
  entry({
    id: 'schedule1',
    name: 'Schedule I',
    group: 'steam',
    accent: '#a3e635',
    status: 'catalog',
    summary: 'Simulador con acciones del chat.',
    mode: 'Steam',
  }),
  entry({
    id: 'repo',
    name: 'R.E.P.O.',
    group: 'coop',
    accent: '#fb7185',
    status: 'catalog',
    summary: 'Co-op de terror con efectos por regalo.',
    mode: 'Co-op',
  }),
  entry({
    id: 'lethal-company',
    name: 'Lethal Company',
    group: 'coop',
    accent: '#94a3b8',
    status: 'catalog',
    summary: 'Eventos en partidas de LC.',
    mode: 'Co-op',
  }),
  entry({
    id: 'ghostwatchers',
    name: 'Ghost Watchers',
    group: 'coop',
    accent: '#c084fc',
    status: 'catalog',
    summary: 'Cazafantasmas interactivo.',
    mode: 'Co-op',
  }),
  entry({
    id: 'rvtheryet',
    name: 'RV There Yet?',
    group: 'coop',
    accent: '#fcd34d',
    status: 'catalog',
    summary: 'Road trip con caos del chat.',
    mode: 'Co-op',
  }),
  entry({
    id: 'megabonk',
    name: 'Megabonk',
    group: 'steam',
    accent: '#f472b6',
    status: 'catalog',
    summary: 'Roguelike con comandos de nivel.',
    mode: 'Steam',
  }),
  entry({
    id: 'ror2',
    name: 'Risk of Rain 2',
    group: 'steam',
    accent: '#818cf8',
    status: 'catalog',
    summary: 'Items y oleadas por eventos.',
    mode: 'Steam',
  }),
  entry({
    id: 'overcooked2',
    name: 'Overcooked 2',
    group: 'steam',
    accent: '#fb923c',
    status: 'catalog',
    summary: 'Cocina caotica para duos.',
    mode: 'Steam',
  }),
  entry({
    id: 'bloonstd6',
    name: 'Bloons TD 6',
    group: 'steam',
    accent: '#facc15',
    status: 'catalog',
    summary: 'Torres y oleadas desde TikTok.',
    mode: 'Steam',
  }),
  entry({
    id: 'geometrydash',
    name: 'Geometry Dash',
    group: 'steam',
    accent: '#22d3ee',
    status: 'catalog',
    summary: 'Saltos y niveles con Geode.',
    mode: 'Steam',
  }),
  entry({
    id: 'ranchsimulator',
    name: 'Ranch Simulator',
    group: 'steam',
    accent: '#84cc16',
    status: 'catalog',
    summary: 'Granja y animales por comandos.',
    mode: 'Steam',
  }),
  entry({
    id: 'twopointedit',
    name: 'Two Point Hospital',
    group: 'steam',
    accent: '#38bdf8',
    status: 'catalog',
    summary: 'Hospital caotico para directos.',
    mode: 'Steam',
  }),
  entry({
    id: 'muck',
    name: 'Muck',
    group: 'steam',
    accent: '#78716c',
    status: 'catalog',
    summary: 'Supervivencia rapida con eventos.',
    mode: 'Steam',
  }),
  entry({
    id: 'tricky-towers',
    name: 'Tricky Towers',
    group: 'steam',
    accent: '#e879f9',
    status: 'catalog',
    summary: 'Torres competitivas.',
    mode: 'Steam',
  }),
  entry({
    id: 'hytale',
    name: 'Hytale',
    group: 'steam',
    accent: '#5eead4',
    status: 'coming',
    summary: 'Preparado para cuando salga el mod.',
    mode: 'Proximamente',
  }),
]

export const GAMING_CATALOG = GAMING_CATALOG_RAW.map((game) => withTikControlGameCover(game))

export function getGamingCatalogEntry(gameId) {
  return GAMING_CATALOG.find((game) => game.id === gameId) || null
}

export function groupCatalogEntries(entries) {
  const byGroup = new Map(GAMING_LIBRARY_GROUPS.map((group) => [group.id, []]))

  for (const game of entries) {
    const groupId = game?.group && byGroup.has(game.group) ? game.group : 'steam'
    const bucket = byGroup.get(groupId)
    if (bucket) {
      bucket.push(game)
    }
  }

  return GAMING_LIBRARY_GROUPS.map((group) => ({
    ...group,
    games: (byGroup.get(group.id) || []).sort((a, b) => a.name.localeCompare(b.name)),
  })).filter((group) => group.games.length > 0)
}