/**
 * Modulos del panel TikControl -> secciones Live Control Studio (base 1:1).
 */
export const TIKCONTROL_MODULES = {
  overview: {
    tikcontrolId: 'inicio',
    label: 'Inicio',
    title: 'Inicio',
    lead: 'Resumen del estudio y accesos rapidos al live.',
    relatedSectionIds: ['live-hub', 'live-ops'],
  },
  actions: {
    tikcontrolId: 'acciones',
    label: 'Acciones',
    title: 'Acciones y eventos',
    lead: 'Automatiza gifts, follows, chat y pruebas en vivo.',
    relatedSectionIds: ['live-ops', 'games'],
    implemented: true,
  },
  sounds: {
    tikcontrolId: 'sonidos',
    label: 'Sonidos',
    title: 'Alertas de sonido',
    lead: 'Biblioteca de alertas de audio por gifts y eventos (base TikControl).',
    relatedSectionIds: ['actions', 'overlay'],
    implemented: true,
    features: [
      'Alertas por gift y evento',
      'Volumen y cola de reproduccion',
      'Integracion MyInstants / archivos propios',
      'Vinculo con acciones del live',
    ],
  },
  tts: {
    tikcontrolId: 'tts',
    label: 'TTS',
    title: 'Texto a voz',
    lead: 'Cola de voz para leer comentarios y alertas.',
    relatedSectionIds: ['actions'],
    implemented: true,
  },
  'widgets-gallery': {
    tikcontrolId: 'widgets',
    label: 'Galeria',
    title: 'Galeria de overlays',
    lead: 'Widgets TikControl originales: likes, monedas, chat, regalos y efectos.',
    relatedSectionIds: ['overlay', 'live-hub'],
    implemented: true,
  },
  overlay: {
    tikcontrolId: 'overlay',
    label: 'Editor',
    title: 'Editor de overlays',
    lead: 'URLs, smart bar, medios y configuracion avanzada.',
    relatedSectionIds: ['widgets-gallery', 'live-hub'],
    implemented: true,
  },
  music: {
    tikcontrolId: 'spotify',
    label: 'Spotify',
    title: 'Musica y song request',
    lead: 'Spotify OAuth, cola y overlay de peticiones.',
    relatedSectionIds: ['widgets-gallery'],
    implemented: true,
  },
  'gifts-hub': {
    tikcontrolId: 'regalos',
    label: 'Regalos',
    title: 'Regalos y catalogo',
    lead: 'Catalogo de gifts TikTok, emotes y vinculo con acciones.',
    relatedSectionIds: ['live-ops', 'actions'],
    features: [
      'Catalogo sincronizado del live',
      'Vista por monedas y rareza',
      'Asignacion rapida a triggers',
      'Historial de regalos de la sesion',
    ],
  },
  battles: {
    tikcontrolId: 'batallas',
    label: 'Batallas',
    title: 'Batallas TikTok LIVE',
    lead: 'PK, linkMicBattle, gift battle y overlays de duelo.',
    relatedSectionIds: ['widgets-gallery', 'live-hub'],
    implemented: true,
  },
  community: {
    tikcontrolId: 'puntos',
    label: 'Comunidad',
    title: 'Comunidad y puntos',
    lead: 'Puntos de viewers, moderacion y perks (base TikControl).',
    relatedSectionIds: ['actions', 'live-ops'],
    implemented: true,
    features: [
      'Puntos por likes, gifts y chat',
      'Moderacion de comandos',
      'Rankings de comunidad',
      'Canje de recompensas',
    ],
  },
  games: {
    tikcontrolId: 'gaming',
    label: 'Gaming',
    title: 'Juegos interactivos',
    lead: 'Biblioteca Steam-style y comandos por juego.',
    relatedSectionIds: ['actions'],
    implemented: true,
  },
  events: {
    tikcontrolId: 'eventos',
    label: 'Eventos',
    title: 'Eventos del canal',
    lead: 'Timer, subastas, notificaciones y metas del live.',
    relatedSectionIds: ['community', 'actions', 'goals'],
    implemented: true,
    features: [
      'Timer y subasta',
      'Event notification overlay',
      'Metas rotativas',
    ],
  },
  agencies: {
    tikcontrolId: 'agencias',
    label: 'Agencias',
    title: 'Agencias',
    lead: 'Panel de agencia TikControl (cloud).',
    relatedSectionIds: ['account'],
    features: ['Explorer de creadores', 'Panel agencia'],
  },
  support: {
    tikcontrolId: 'soporte',
    label: 'Soporte',
    title: 'Soporte',
    lead: 'Ayuda, logs y enlaces de diagnostico.',
    relatedSectionIds: ['bridges', 'account'],
    implemented: true,
  },

  account: {
    tikcontrolId: 'cuenta',
    label: 'Cuenta',
    title: 'Cuenta y plan',
    lead: 'Perfil TikControl-style: plan, login y preferencias.',
    relatedSectionIds: ['profiles', 'bridges'],
    features: [
      'Plan Free / Premium',
      'Sesion TikTok',
      'Preferencias de idioma',
      'Acuerdos beta',
    ],
  },
  bridges: {
    tikcontrolId: 'integraciones',
    label: 'Integraciones',
    title: 'Integraciones',
    lead: 'OBS, Streamer.bot, StreamDeck, bridges locales.',
    implemented: true,
    relatedSectionIds: ['overlay', 'games'],
  },
  storage: {
    tikcontrolId: 'almacenamiento',
    label: 'Almacenamiento',
    title: 'Almacenamiento en la nube',
    lead: '5 GB Premium para imagenes, audio y video de alertas.',
    relatedSectionIds: ['overlay', 'sounds'],
    implemented: true,
    features: [
      'Subida de medios',
      'Uso por perfil',
      'Enlaces para overlays',
    ],
  },
  goals: {
    tikcontrolId: 'goals',
    label: 'Metas',
    title: 'Metas del live',
    lead: 'Barras de meta: likes, monedas, follows, shares, subs.',
    relatedSectionIds: ['widgets-gallery', 'live-hub'],
    implemented: true,
    features: [
      'Goals de likes',
      'Goals de monedas',
      'Goals de follows / shares',
      'Rotacion de metas',
    ],
  },
  profiles: {
    tikcontrolId: 'perfiles',
    label: 'Perfiles',
    title: 'Perfiles preconfigurados',
    lead: 'Cambia entre setups de acciones, sonidos y overlays.',
    relatedSectionIds: ['account', 'storage'],
    implemented: true,
    features: [
      'Perfil activo',
      'Importar / exportar perfil',
      'Plantillas de la comunidad',
    ],
  },
  'live-hub': {
    tikcontrolId: 'live-hub',
    label: 'Centro live',
    title: 'Centro en vivo',
    implemented: true,
  },
  'live-ops': {
    tikcontrolId: 'live-ops',
    label: 'TikTok',
    title: 'TikTok Live',
    implemented: true,
  },
}

export function getTikcontrolModule(sectionId) {
  return TIKCONTROL_MODULES[sectionId] || null
}